project:
  type: website
  output-dir: _site

website:
  title: "Yue Cao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume.qmd
        text: Resume
      - href: project.qmd
        text: Project

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



