project:
  type: website
  output-dir: _site
execute:
  freeze: auto
website:
  title: "Yue Cao"
  site-url: https://cyi9.github.io/Cy19.github.io/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume.qmd
        text: Resume
      - href: project.qmd
        text: Project

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



